### ISSUE TITLE
Missing information in the guide

### ISSUE THREAD

**Issue by powershellwhizz** [Cj-Scott/Get-AppRegistrationExpiration#6]
Your Readme file does not talk about how the Automation Account should be setup, can you add a section for this please?

For example, the main question I have is how often does the runbook need to run? can you just run it once? I assume it needs to run at least as often as you add new RunAs/SPNs so that it detects them and sends them to the log analytics workspace. If yes, it would be helpful to say this in your guide.

Thanks,

**Comment by Cj-Scott** [comment]
Hello, 
I didn't want to include Azure Automation specific configurations because there are so many well documented sources out there already. I also didnt include the schedule because the needs of every organization differ, if you are unsure of a schedule I would recommend running the runbook Daily and the alert schedule daily

[Azure Automation Setup](https://docs.microsoft.com/en-us/azure/automation/)
[Alert Setup](https://docs.microsoft.com/en-us/azure/azure-monitor/alerts/alerts-log) For Daily use 1440 for Period and Frequency. I will be adding the log query to the repo here shortly.
